<div class="row">
    <div class="col-lg-6">
        <div class="well bs-component">
            <form class="form-horizontal" method="post">
                <fieldset>
                    <legend>Легковые</legend>
                    <div class="form-group">
                        <label for="inputPrice" class="col-lg-3 control-label">Цена авто</label>
                        <div class="col-lg-9">
                            <input type="number" min="100" class="form-control" id="inputPrice" name="price" required >
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="select" class="col-lg-3 control-label">Двигатель</label>
                        <div class="col-lg-4">
                            <select class="form-control" id="select" name="engine">
                                <?php for ($i = 0.5,$j = 500;$i < 20.1; $i+=0.1 ,$j+=100):?>
                                <option value="<?=$j?>"><?=$i?></option>
                                <?php endfor;?>
                            </select>
                        </div>
                        <div class="col-lg-5">
                            <select class="form-control" id="select" name="fuel">
                                <option value="bensin">Бензин</option>
                                <option value="diesel">Дизель</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputAge" class="col-lg-3 control-label">Возраст авто</label>
                        <div class="col-lg-9">
                            <select class="form-control" id="select" name="age">
                                <option value="0">новое</option>
                                <option value="3">до 5 лет</option>
                                <option value="6">5-8 лет</option>
                                <option value="9">более 8 лет</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-3">
                        </div>
                        <div class="col-lg-9">
                            <button type="submit" class="btn btn-primary">Рассчитать</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
    <div class="col-lg-6">
        <?php if($_POST):?>
        <div class="bs-component">
            <table class="table table-striped table-hover ">
                <thead>
                <tr>
                    <th>Цена авто</th>
                    <th></th>
                    <th></th>
                    <th><?= $price.' $'?></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>НДС</td>
                    <td>20%</td>
                    <td></td>
                    <td><?= $vat.' $'?></td>
                </tr>
                <tr>
                    <td>Пошлина</td>
                    <td>10%</td>
                    <td></td>
                    <td><?= $duty.' $'?></td>
                </tr>
                <tr>
                    <td>Акциз</td>
                    <td><?= $rate.' $'?> за см<sup>3</sup></td>
                    <td></td>
                    <td><?= $excise.' $'?></td>
                </tr>
                <tr >
                    <td>Налог в пенс. фонд</td>
                    <td>5%</td>
                    <td></td>
                    <td><?= $tax.' $'?></td>
                </tr>
                <tr>
                    <td>Сертификация и оформление авто</td>
                    <td></td>
                    <td></td>
                    <td><?= $certific.' $'?></td>
                </tr>
                <tr>
                    <th>Стоимость самой растаможки</th>
                    <th></th>
                    <th></th>
                    <th><?= $cost.' $'?></th>
                </tr>
                <tr class="success">
                    <th>Цена с растаможкой</th>
                    <th></th>
                    <th></th>
                    <th><?= $amount.' $'?></th>
                </tr>
                </tbody>
            </table>
        </div><!-- /example -->
        <?php endif;?>
    </div>
</div>
