<div class="row">
    <div class="col-lg-6">
        <div class="well bs-component">
            <form class="form-horizontal" method="post">
                <fieldset>
                    <legend>Мото</legend>
                    <div class="form-group">
                        <label for="inputPrice" class="col-lg-3 control-label">Цена авто</label>
                        <div class="col-lg-9">
                            <input type="number" min="100" class="form-control" id="inputPrice" name="price" placeholder="$" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEngine" class="col-lg-3 control-label" >Двигатель</label>
                        <div class="col-lg-9">
                            <input type="number" min="10" class="form-control" id="inputEngine" name="engine" placeholder="см3" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-3">
                        </div>
                        <div class="col-lg-9">
                            <button type="submit" class="btn btn-primary">Рассчитать</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
    <div class="col-lg-6">
        <?php if($_POST):?>
            <div class="bs-component">
                <table class="table table-striped table-hover ">
                    <thead>
                    <tr>
                        <th>Цена авто</th>
                        <th></th>
                        <th></th>
                        <th><?= $price.' $'?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>НДС</td>
                        <td>20%</td>
                        <td></td>
                        <td><?= $vat.' $'?></td>
                    </tr>
                    <tr>
                        <td>Пошлина</td>
                        <td>10%</td>
                        <td></td>
                        <td><?= $duty.' $'?></td>
                    </tr>
                    <tr>
                        <td>Акциз</td>
                        <td><?= $rate.' $'?> за см<sup>3</sup></td>
                        <td></td>
                        <td><?= $excise.' $'?></td>
                    </tr>
                    <tr >
                        <td>Налог в пенс. фонд</td>
                        <td>5%</td>
                        <td></td>
                        <td><?= $tax.' $'?></td>
                    </tr>
                    <tr>
                        <td>Сертификация и оформление авто</td>
                        <td></td>
                        <td></td>
                        <td><?= $certific.' $'?></td>
                    </tr>
                    <tr>
                        <th>Стоимость самой растаможки</th>
                        <th></th>
                        <th></th>
                        <th><?= $cost.' $'?></th>
                    </tr>
                    <tr class="success">
                        <th>Цена с растаможкой</th>
                        <th></th>
                        <th></th>
                        <th><?= $amount.' $'?></th>
                    </tr>
                    </tbody>
                </table>
            </div><!-- /example -->
        <?php endif;?>
    </div>
</div>
